---

- include_role:
    name: namespace
  vars:
    namespace: "{{ fuse_namespace }}"
    display_name: "Shared Fuse Online"

- name: Add labels to namespace
  shell: oc label --overwrite namespace {{ fuse_namespace }} {{ monitoring_label_name }}={{ monitoring_label_value }} integreatly-middleware-service=true
  register: namespace_label
  failed_when: namespace_label.stderr != '' and 'not labeled' not in namespace_label.stderr
  changed_when: namespace_label.rc == 0

- name: Create Syndesis CRD
  shell: oc create -f {{ fuse_online_crd_resources }}
  register: create_crd
  failed_when: create_crd.stderr != '' and 'AlreadyExists' not in create_crd.stderr

- name: Create Fuse image streams
  shell: "oc replace --force -f {{ fuse_online_imagestream_resources }} -n openshift"
  register: fuse_create_imagestream
  failed_when: fuse_create_imagestream.stderr != '' and 'AlreadyExists' not in fuse_create_imagestream.stderr
  changed_when: fuse_create_imagestream.rc == 0

- name: Create fuse Operator resources in {{ fuse_namespace }}
  shell: oc create -f {{ fuse_online_operator_resources }} -n {{ fuse_namespace }}
  register: create_operator_resources
  failed_when: create_operator_resources.stderr != '' and 'AlreadyExists' not in create_operator_resources.stderr

- template:
    src: syndesis-customresource.yml.j2
    dest: /tmp/syndesis-customresource.yml

- name: Create Syndesis custom resource in {{ fuse_namespace }}
  shell: oc create -f /tmp/syndesis-customresource.yml -n {{ fuse_namespace }}
  register: create_cr
  failed_when: create_cr.stderr != '' and 'AlreadyExists' not in create_cr.stderr

- name: Verify Fuse deployment succeeded
  shell: oc get pods -n {{ fuse_namespace }} -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w | tr -d ' '
  register: fuse_verify_result
  until: fuse_verify_result.stdout | int > 7
  retries: 50
  delay: 10
  changed_when: False

# Allow any authenticated user to access fuse. Sleep 5 to allow time for the
# new deployment to kick off.
- name: Remove OpenShift SAR configuration on Fuse Managed OAuth proxy
  shell: oc get dc syndesis-oauthproxy -o yaml -n {{ fuse_namespace }} | sed '/--openshift-sar/d' | oc apply -f - -n {{ fuse_namespace }}; sleep 5

- name: Verify Fuse deployment succeeded
  shell: oc get pods -n {{ fuse_namespace }} -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w | tr -d ' '
  register: fuse_verify_result
  until: fuse_verify_result.stdout | int > 7
  retries: 50
  delay: 10
  changed_when: False
