---
- name: Create Fuse Console templates
  shell: oc create -f {{ fuse_resource_base }}/{{ item }} -n openshift
  with_items:
    - "fuse-apicurito.yml"
  register: create_fuse_console_template_cmd
  failed_when: create_fuse_console_template_cmd.stderr != '' and 'AlreadyExists' not in create_fuse_console_template_cmd.stderr
  changed_when: create_fuse_console_template_cmd.rc == 0