---

- import_tasks: admin_token.yml

- name: Retrieve 3Scale users
  uri:
    url: "https://{{ threescale_admin_route }}/admin/api/users.xml"
    method: GET
    return_content: yes
    dest: /tmp/3scale_users.xml
    body: "access_token={{ threescale_admin_token }}&role=admin"
    validate_certs: "{{ threescale_sso_validate_certs }}"
    status_code: [200]

- name: Create evaluation user
  include: _user.yml email={{ threescale_evals_email }} username={{ threescale_evals_username }} password={{ threescale_evals_password }}

- name: Create evaluation admin user
  include: _user.yml email={{ rhsso_evals_admin_email }} username={{ rhsso_evals_admin_username }} password={{ rhsso_evals_admin_password }}

- name: Seed evaluation users
  include: _user.yml email={{ rhsso_seed_users_email_format|format(item|int) }} username={{ rhsso_seed_users_name_format|format(item|int) }} password={{ rhsso_seed_users_password }}
  with_sequence: count={{ rhsso_seed_users_count }}
