---
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
      upgrade_msb_image: quay.io/integreatly/managed-service-broker:v0.0.4
      upgrade_webapp_image: quay.io/integreatly/tutorial-web-app:v2.9.0
      upgrade_webapp_operator_image: quay.io/integreatly/tutorial-web-app-operator:v0.0.12
      upgrade_sso_operator_image: quay.io/integreatly/keycloak-operator:v1.3.4

    - name: Check current version
      shell: "oc get secret manifest -n {{ eval_webapp_namespace }} -o json | jq \".data.generated_manifest\" -r | base64 -d | jq \".version\" -r"
      register: version

    - fail:
        msg: "The current installation could not be verified as the manifest could not be read"
      when: version.stderr != ""
    - fail:
        msg: "The installed version must be 1.3.0 to run this upgrade playbook, {{ version.stdout }} is currently installed"
      when: version.stdout != "release-1.3.0"

    # SSO
    - name: Update keycloak-operator image tag
      shell: "oc patch deployment keycloak-operator -n {{ eval_rhsso_namespace }} --type json -p '[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"{{ upgrade_sso_operator_image }}\"}]'"

    - name: add CreateOnly to openshift keycloak realm
      shell: "oc patch keycloakrealm openshift -n {{ eval_rhsso_namespace }} --type json -p '[{\"op\": \"add\", \"path\": \"/spec/createOnly\", \"value\": true}]'"

    # Managed Service Broker
    - name: Retrieve SSO host
      shell: oc get route sso -n {{ eval_rhsso_namespace }} -o jsonpath='{.spec.host}'
      register: get_sso_host
    - set_fact:
        upgrade_sso_url: "https://{{ get_sso_host.stdout | trim }}/auth/admin/openshift/console"

    - name: Append the SSO_URL env to the Managed Service Broker deployment
      shell: oc patch deployment msb -n {{ eval_msbroker_namespace }} --type=json -p '[{"op":"add","path":"/spec/template/spec/containers/0/env/-1","value":{"name":"SSO_URL","value":"{{ upgrade_sso_url }}"}}, {"op":"replace","path":"/spec/template/spec/containers/0/image","value":"{{ upgrade_msb_image }}"}]'
      register: upgrade_msb
      failed_when: upgrade_msb.stderr != '' and 'not patched' not in upgrade_msb.stderr

    # Solution Explorer
    - name: Bump the Web App operator version to 0.0.12
      shell: oc patch deployment tutorial-web-app-operator -n {{ eval_webapp_namespace }} --type json -p '[{"op":"replace", "path":"/spec/template/spec/containers/0/image", "value":"{{ upgrade_webapp_operator_image }}"}]'
      register: upgrade_webapp_operator
      failed_when: upgrade_webapp_operator.stderr != '' and 'not patched' not in upgrade_webapp_operator.stderr

    - name: Bump the Web App deployment version to 0.0.12
      shell: oc patch dc tutorial-web-app -n {{ eval_webapp_namespace }} --type json -p '[{"op":"replace", "path":"/spec/template/spec/containers/0/image", "value":"{{ upgrade_webapp_image }}"}]'
      register: upgrade_webapp
      failed_when: upgrade_webapp.stderr != '' and 'not patched' not in upgrade_webapp.stderr

